#!/bin/bash
source "$(dirname $0)/common"

cd $BUILD_DIR

# remove auxiliary files
find . -type f ! -name '*.pdf' ! -name '.gitignore' | xargs -r rm
rm -r _minted-*

# reorganize files for release
mkdir chapters

shopt -s extglob # it extends regexes
mv !("main.pdf") ./chapters

zip -r "release.zip" chapters main.pdf
# zip -r "release-$(date +"%Y.%m.%d_%H.%M").zip" chapters main.pdf
