#!/bin/bash

# https://stackoverflow.com/questions/59895
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BASE_DIR="${SCRIPT_DIR}/../.."
CHAPTERS_DIR="${SCRIPT_DIR}/../../chapters"
SETTINGS_DIR="${SCRIPT_DIR}/../../settings"
BUILD_DIR="${SCRIPT_DIR}/../../build"
ALGORITHMS_DIR="${SCRIPT_DIR}/../../assets/algorithms"
