#!/bin/bash
source "$(dirname $0)/common"
source "$(dirname $0)/reset-project"

echo ""
echo "COMPILO PREAMBOLO PRINCIPALE ELIMINANDO EVENTUALI FILE AUSILIARI PRODOTTI"
echo ""
read -rsp $'Press enter to continue...\n'

cd $BASE_DIR/settings
pdflatex --shell-escape -ini -jobname="preamble.main" "&pdflatex ./preamble.main.sty\dump"
rm -f preamble.main.log

clear
echo ""
echo "COMPILO PREAMBOLO ALGORITMI ELIMINANDO EVENTUALI FILE AUSILIARI PRODOTTI"
echo ""
read -rsp $'Press enter to continue...\n'

cd $BASE_DIR/assets/algorithms
pwd
pdflatex -ini -jobname="preamble" "&pdflatex preamble.sty\dump"
rm -f preamble.log
