#!/bin/bash
source "$(dirname $0)/common"

cd $SETTINGS_DIR

echo "cancello il preambolo pre-compilato del main"
rm -f preamble.main.log
rm -f preamble.main.fmt

echo "cancello log e preambolo degli algoritmi"
cd $ALGORITHMS_DIR
rm -f preamble.log
rm -f preamble.fmt

echo "pulizia dei file generali"
cd $BASE_DIR
latexmk -C
