#!/bin/bash

# https://stackoverflow.com/questions/59895
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SRC_DIR="${SCRIPT_DIR}"/../..
CHAPTERS_DIR="${SRC_DIR}/chapters"
SETTINGS_DIR="${SRC_DIR}/settings"
BUILD_DIR="${SRC_DIR}/build"
ALGORITHMS_DIR="${SRC_DIR}/assets/algorithms"
