#!/bin/bash

# https://stackoverflow.com/questions/59895
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
BASE_DIR="${SCRIPT_DIR}"/../..
CHAPTERS_DIR="${BASE_DIR}/chapters"
SETTINGS_DIR="${BASE_DIR}/settings"
BUILD_DIR="${BASE_DIR}/build"
ALGORITHMS_DIR="${BASE_DIR}/assets/algorithms"

# DEBUG
echo SCRIPT_DIR=$SCRIPT_DIR
echo BASE_DIR=$BASE_DIR
echo CHAPTERS_DIR=$CHAPTERS_DIR
echo SETTINGS_DIR=$SETTINGS_DIR
echo BUILD_DIR=$BUILD_DIR
echo ALGORITHMS_DIR=$ALGORITHMS_DIR
