#!/bin/bash

echo ""
echo "COMPILO PREAMBOLO PRINCIPALE ELIMINANDO EVENTUALI FILE AUSILIARI PRODOTTI"
echo ""
cd src/settings
pdflatex --shell-escape --interaction=batchmode -ini -jobname="preamble.main" "&pdflatex ./preamble.main.sty\dump"
rm -f preamble.main.log
cd ../..

echo ""
echo "COMPILO PREAMBOLO ALGORITMI ELIMINANDO EVENTUALI FILE AUSILIARI PRODOTTI"
echo ""
cd src/assets/algorithms
pdflatex --interaction=batchmode -ini -jobname="preamble" "&pdflatex preamble.sty\dump"
rm -f preamble.log
cd ../../..
