latexmk -C
arara bfs-proc
arara cc-alt
arara cc-dfs
arara cc
arara dfs-schema
arara dfs-stack-explicit
arara dfs-stack-implicit
arara dfs-stack
arara erdos
arara graph-interface
arara hasCycle
arara hasCycleDAG
arara hasCycleRec
arara kosaraju
arara larghezzaAlberoRadicato
arara maxDist
arara printPath
arara quadrato
arara scc
arara topSort
arara topSort-dfs
arara transpose
arara visita-albero
arara visita-grafo
