latexmk -C
arara concatenateABRTrees
arara dict-abr-constructor
arara dict-abr-insert
arara dict-abr-insertNode
arara dict-abr-lookup
arara dict-abr-min-max
arara dict-abr-remove
arara dict-abr-removeNode
arara dict-abr-succ-pred
arara insertNodeRec
arara minDistance
arara shortcut
arara tree-abr-interface
arara tree-rb-balanceDelete
arara tree-rb-balanceInsert
arara tree-rb-insertNode
arara tree-rb-interface
arara tree-rb-leftRotation
arara tree-rb-rightRotation
arara verifyABR
